spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leadnews_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456a
  redis:
    host: 127.0.0.1
    password: 123456a
    port: 6379
# 设置Mapper接口所对应的xml文件位置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.heima.model.user.pojos